import RecruitHeader from "@/components/recruit/recruit-header";
import Footer from "@/components/recruit/footer";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Privacy Policy | RecruitPalz",
  description: "Read RecruitPalz's privacy policy to understand how we collect, use, and protect your personal data.",
};

export default function PrivacyPolicy() {
  return (
    <>
      <RecruitHeader />
      <div className="min-h-screen bg-background">
        <div className="max-w-4xl mx-auto px-4 py-16">
          <h1 className="text-4xl font-bold text-foreground mb-8">Privacy Policy</h1>
          <div className="prose prose-lg max-w-none text-muted-foreground">
            <p className="text-sm mb-8">Last updated: January 23, 2026</p>

            <p className="mb-6">
              This Privacy Policy describes RecruitPalz's policies and procedures on the collection, use, and disclosure of your information when you use our service and tells you about your privacy rights and how the law protects you. We use your personal data to provide and improve our services. By using the service, you agree to the collection and use of information in accordance with this Privacy Policy.
            </p>

            <h2 className="text-2xl font-semibold text-foreground mt-8 mb-4">Interpretation</h2>
            <p className="mb-6">
              The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
            </p>

            <h2 className="text-2xl font-semibold text-foreground mt-8 mb-4">Definitions</h2>
            <p className="mb-4">For the purposes of this Privacy Policy:</p>
            <ul className="list-disc pl-6 mb-6 space-y-2">
              <li><strong>Account</strong> means a unique account created for you to access our Service or parts of our Service.</li>
              <li><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to RecruitPalz.</li>
              <li><strong>Cookies</strong> are small files that are placed on your computer, mobile device, or any other device by a website, containing the details of your browsing history on that website among its many uses.</li>
              <li><strong>Country</strong> refers to: United States.</li>
              <li><strong>Device</strong> means any device that can access the Service such as a computer, cellphone, or a digital tablet.</li>
              <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
              <li><strong>Service</strong> refers to RecruitPalz's Website and products.</li>
              <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service, or to assist the Company in analyzing how the Service is used.</li>
              <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
              <li><strong>Website</strong> refers to RecruitPalz, accessible from www.recruitpalz.com</li>
              <li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
            </ul>

            <h2 className="text-2xl font-semibold text-foreground mt-8 mb-4">Collecting and Using Personal Data</h2>
            <h3 className="text-xl font-semibold text-foreground mt-6 mb-3">Types of Data Collected</h3>

            <h4 className="text-lg font-semibold text-foreground mt-4 mb-2">Personal Data</h4>
            <p className="mb-4">
              While using RecruitPalz, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you. Personally identifiable information may include, but is not limited to:
            </p>
            <ul className="list-disc pl-6 mb-6 space-y-2">
              <li>Email address</li>
              <li>First name and last name</li>
              <li>Phone number</li>
              <li>Address, State, Province, ZIP/Postal code, City</li>
              <li>Usage Data</li>
            </ul>

            <h4 className="text-lg font-semibold text-foreground mt-4 mb-2">Usage Data</h4>
            <p className="mb-4">Usage Data is collected automatically when using the service.</p>
            <p className="mb-4">
              Usage Data may include information such as your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
            </p>
            <p className="mb-6">
              When you access the Service by or through a mobile device, we may collect certain information automatically, including, but not limited to, the type of mobile device you use, your mobile device unique ID, the IP address of your mobile device, your mobile operating system, the type of mobile Internet browser you use, unique device identifiers and other diagnostic data. We may also collect information that your browser sends whenever you visit our Service or when you access the Service by or through a mobile device.
            </p>

            <h4 className="text-lg font-semibold text-foreground mt-4 mb-2">Tracking Technologies and Cookies</h4>
            <p className="mb-4">
              We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service.
            </p>

            <h2 className="text-2xl font-semibold text-foreground mt-8 mb-4">Children's Privacy</h2>
            <p className="mb-6">
              Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If you are a parent or guardian and you are aware that your child has provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from anyone under the age of 13 without verification of parental consent, we take steps to remove that information from our servers.
            </p>

            <h2 className="text-2xl font-semibold text-foreground mt-8 mb-4">Links to Third-Party Websites</h2>
            <p className="mb-6">
              Our Service may contain links to other websites that are not operated by us. If you click on a third party link, you will be directed to that third party's site. We strongly advise you to review the Privacy Policy of every site you visit. We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.
            </p>

            <h2 className="text-2xl font-semibold text-foreground mt-8 mb-4">Changes to this Privacy Policy</h2>
            <p className="mb-6">
              We may update Our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page. We will let you know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the "Last updated" date at the top of this Privacy Policy. You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.
            </p>

            <h2 className="text-2xl font-semibold text-foreground mt-8 mb-4">Contact Us</h2>
            <p className="mb-2">
              If you have any questions about this Privacy Policy, you can contact us:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li>By email: <a href="mailto:support@recruitpalz.com" className="text-primary hover:underline">support@recruitpalz.com</a></li>
            </ul>
          </div>
        </div>
      </div>
      <Footer />
    </>
  );
}
